### ISSUE TITLE
SNOW-1333232 High Severity DoS CVE in introduced - github.com/hambra/avro

### ISSUE THREAD

**Issue by ChronosMasterOfAllTime** [snowflakedb/gosnowflake#1101]
Please answer these questions before submitting your issue. 
In order to accurately debug the issue this information is required. Thanks!

1. What version of GO driver are you using? 1.9

   
2. What operating system and processor architecture are you using? MacOS x86_64

   
3. What version of GO are you using? 1.22
run `go version` in your console

4.Server version: **N/A**

5. What did you do?

Upgraded to v1.9 of the Snowflake driver. Apache Arrow v15.0.0 is using a version of the `github.com/hambra/avro` that introduces a DoS exploit.  This is fixed in the latest version of Apache Arrow

See [Snyk issue](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMHAMBAAVRO-5777730)

Fixed in v16.0.0 of Apache Arrow [go.mod](https://github.com/apache/arrow/blob/7003e90c113cec58a620deddf56af71eb305af2a/go/go.mod#L50)

6. What did you expect to see?

   No High CVE exploits

7. Can you set logging to DEBUG and collect the logs?

   https://community.snowflake.com/s/article/How-to-generate-log-file-on-Snowflake-connectors
   
8. What is your Snowflake account identifier, if any? databots

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for drawing attention to this issue and also for the PR ! can we please wait for Arrow v16 to be available?

**Comment by ChronosMasterOfAllTime** [comment]
@sfc-gh-dszmolka We can wait if you're more comfortable with an official release

[This commit](https://github.com/hamba/avro/commit/20c2c8e96d3a25dd1543232355229608d93403f4) fixed the DoS which was released in hamba/avro v2.19.0.

**Comment by ChronosMasterOfAllTime** [comment]
Good catch though; I brought this up with the Snyk team as a potential false positive. Will report back here

**Comment by sfc-gh-dszmolka** [comment]
Thanks for the additional details, indeed Arrow seems to have bumped the hamba/avro to past 2.19 ([2.20.1](https://github.com/apache/arrow/blob/main/go/go.mod#L50)) in the latest (yet unreleased) code. 

Of course the team will review your PR but from what I saw we usually prefer depending on official released code. Good to have this on the table though, so really appreciate !

**Comment by sfc-gh-dszmolka** [comment]
@ChronosMasterOfAllTime Arrow v16 looks to be released now, can you please modify your PR to have the official released v16.0.0 ?

**Comment by sfc-gh-dszmolka** [comment]
A quick update: we cannot just simply merge the PR. Reason being ([as you might have noticed from the tests](https://github.com/snowflakedb/gosnowflake/pull/1114)) , all tests are for this PR failing for go1.19 as Arrow v16 would need go1.20 at least.

Until Snowflake drops support for go1.19, we cannot merge this PR or else it would break the driver for everyone on go1.19 currently. Likely we would also require a new major version released from the driver.

So we must take appropriate care. 

This is to set expectations why this 'simple' Arrow version bump won't be very very quickly merged.

Also on the side note, the question is still open: **can you perhaps please advise what is the actual 'High Severity DoS CVE' / vulnerability which is there in Arrow v15.0.2 and supposed to be addressed in Arrow v16** ?

It is likely not the one linked to this issue originally:
* Snyk: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMHAMBAAVRO-5777730
* cve.org [CVE-2023-37475](https://www.cve.org/CVERecord?id=CVE-2023-37475) 
* GH advisory: https://github.com/advisories/GHSA-9x44-9pgq-cf45

because it is addressed in avro 2.13 and arrow v15 on which we are already depends on avro 2.17 which is not vulnerable to this CVE. 
Clarification is really appreciated !

**Comment by sfc-gh-dszmolka** [comment]
Thank you  for following up with Snyk and the feedback - as there's no vulnerability, closing the issue for now. The bump to Arrow v16 will still happen though, eventually.

**Comment by sfc-gh-dszmolka** [comment]
As a followup, separately from the CVE concern, which is already resolved for months.

Arrow is now bumped to v16, and will be released with November 2024 releas cycle of the gosnowflake driver. Thank you for the contribution!
