### ISSUE TITLE
How can I use prepared statements / bind variables in an ALTER SESSION statement?

### ISSUE THREAD

**Issue by hasryan** [snowflakedb/gosnowflake#219]
### Issue description

I am attempting to set a session-level QUERY_TAG using the syntax described at https://docs.snowflake.net/manuals/sql-reference/sql/alter-session.html .  Part of my query tag may include values that are passed in from an external source.  For this reason I would like to ensure that I safely set the QUERY_TAG parameter without risking SQL injection.

I don't know if this is a bug or if it is intended behavior.  If it is intended, is there a suggested alternative method to achieve my goal?  I cannot include the QUERY_TAG in my connection DSN since I use client-side connection pooling and need to change the tag several times per connection.

### Example code

```
queryTag := buildTag()
db.ExecContext(context.TODO(), "ALTER SESSION SET QUERY_TAG=?", queryTag)
```

### Error log

The `queryTag` variable is ignored, and the QUERY_TAG is set to the literal string `?`

### Configuration

*Driver version (or git SHA):* https://github.com/snowflakedb/gosnowflake/releases/tag/v1.1.16

*Go version:* 1.10

*Server version:* 3.15.2

*Client OS:* macOS 10.14

**Comment by howryu** [comment]
This is currently not supported.

**Comment by smtakeda** [comment]
This is a general binding issue and not specific to Golang driver. Please reach out the customer support to raise an enhancement request.

**Comment by leonzakaim** [comment]
When it will be supported?

**Comment by sfc-gh-dszmolka** [comment]
thank you for your interest ! Two things: 
1. as mentioned by my colleague, the original request described in this Issue is not related to the Gosnowflake driver, or any of the drivers. It needs to be implemented on the server side. To raise an enhancement request against the Snowflake backend capabilities, do reach out to your Snowflake Account Team please. 

2. the particular use-case, applying QUERY_TAG : it is already supported with setting [WithQueryTag](https://pkg.go.dev/github.com/snowflakedb/gosnowflake#WithQueryTag) on the context.
