### ISSUE TITLE
Null types:  unsupported Scan, storing driver.Value type <nil> into type *time.Time

### ISSUE THREAD

**Issue by kheraankit** [snowflakedb/gosnowflake#273]
### Issue description
Try to fetch a row from a table that has a TIMESTAMP_LTZ or other date/time column type and make sure the value in the table for that column is null.   Use the scan method to fetch the row and provide a *time.Time destination to scan the value of the column into.

What should happen?
Provide a NullTime type as provided by other drivers
What's happening?
unsupported Scan, storing driver.Value type <nil> into type *time.Time

**Comment by smtakeda** [comment]
Is this go1.13 new feature?

**Comment by kheraankit** [comment]
The way I am trying to get around is by defining my own NullTime type but feel that the driver should provide this type and do the conversion etc... if needed.

```
type NullTime struct {
	Time  time.Time
	Valid bool // Valid is true if Time is not NULL
}

// Scan implements the Scanner interface for NullTime
func (nt *NullTime) Scan(value interface{}) error {
	if value == nil {
		nt.Time, nt.Valid = time.Time{}, false
		return nil
	}

	switch v := value.(type) {
	case time.Time:
                // . snowflake already has converted to time.Time
		nt.Time, nt.Valid = v, true
		return nil
	}
	return fmt.Errorf("Can't convert %T to time.Time", value)
}
```

**Comment by smtakeda** [comment]
I'm a bit confused. `NullTime` is provided from Go 1.13, and other database started deprecating their own `NullTime`:
- https://github.com/go-sql-driver/mysql/issues/960
- https://github.com/lib/pq/issues/902
Why Snowflake needs to introduce it now?

In my understanding, `NullTime` was added to other drivers, because it didn't exist before. Now why not upgrading Go to 1.13? Do I miss something? Can you please elaborate your use case?

**Comment by dolmen** [comment]
@kheraankit Could you check @smtakeda 's answer and close this issue?
