### ISSUE TITLE
Question: When to enable KeepSessionAlive config setting?

### ISSUE THREAD

**Issue by craigpg** [snowflakedb/gosnowflake#477]
### Question
Would appreciate some guidance on which use case(s) one would want to set `KeepSessionAlive` to `true`, especially since this setting is separate from, and seemingly unrelated to, the `client_keep_session_alive` param which controls the heartbeat.

I see that it prevents closing the session when the connection is closed, but unsure of the circumstances where this would be necessary.

Is this to support multiple calls to `sql.OpenDB` such that you can close one and not impact the others?

### Example code
```go
type Config struct {
  ...
  
  KeepSessionAlive bool          // Enables the session to persist even after the connection is closed

  ...
}
```

**Comment by sfc-gh-jbahk** [comment]
Hi @craigpg, this is an internal parameter which is used when you want to be able to close the sql.db object and release its resources but not actually call .Close() so that the Snowflake session is not alive. We have purposely not documented this as it's an internal parameter and don't see a use case for most Go driver users. Please let me know if you have additional questions.
