### ISSUE TITLE
SNOW-679254: Properly support arrays as returned type

### ISSUE THREAD

**Issue by Thomasdezeeuw** [snowflakedb/gosnowflake#674]
### Issue description

Currently arrays are returned a strings, which is not ideal because that means we have to parse those manually.

**Comment by yevgenypats** [comment]
Hi there! I also stumbled upon this and I would add that it's not a question of ideal or not but rather there is no way to parse as if there is something like `","` inside a string saved in a string array you wont be able to distinguish between what is part of the array and what is part of the string in go.

**Comment by sfc-gh-dszmolka** [comment]
thank you for raising this issue - even bigger thank you to yevgenypats for answering it. closing it for now, but if there's a PR which could address the requirement I'm happy to reopen to move forward

**Comment by Thomasdezeeuw** [comment]
@sfc-gh-dszmolka can you reopen this as it's not solved.

**Comment by sfc-gh-dszmolka** [comment]
reopening the issue and marking it as an enhancement for the product team to pick up in a later time

**Comment by sfc-gh-pfus** [comment]
Hi all, thank you for your patience. Snowflake introduced a concept of structured types ([doc](https://docs.snowflake.com/en/sql-reference/data-types-structured)). Driver also supports these types since version 1.11.0 ([doc](https://pkg.go.dev/github.com/snowflakedb/gosnowflake#hdr-Semistructured_and_structured_types)).
