### ISSUE TITLE
Expecting OBJECT but got VARCHAR when inserting a JSON value. 

### ISSUE THREAD

**Issue by mattj150** [snowflakedb/gosnowflake#995]
1. What version of GO driver are you using? 1.7.0
2. What operating system and processor architecture are you using? M1 Macbook pro
4. What version of GO are you using? 1.21.4
5. Server version: 7.43.0

7. What did you do?

I am attempting to INSERT a JSON object to an OBJECT column in snowflake.  When running the below code I get the following error:

```
Expression type does not match column data type, expecting OBJECT but got VARCHAR(4) for column object
```

```
statement := fmt.Sprintf(`
		INSERT INTO %s (v1,v2,v3,v4,v5,object) 
		VALUES (?, ?, ?, ?, ?, ?)`,
		table)

j, err := json.Marshal("{}")
	if err != nil {
		return err
	}

_, err = db.Exec(statement, v1, v2, v3, v4, v5, string(j))
```

I didn't see anything in the docs on how to do this correctly, do I need to convert the JSON string to some other type of object? 

8. What did you expect to see?

JSON Object inserted correctly.

**Comment by sfc-gh-dszmolka** [comment]
hi and thank you for raising this issue! can you please try to do something like in https://github.com/snowflakedb/gosnowflake/issues/217#issuecomment-1514234356 (difference is the column type was `VARIANT` instead of `OBJECT` but i'm wondering if it works with that as well)

let us know please how it went

**Comment by sfc-gh-dszmolka** [comment]
added an example in https://github.com/snowflakedb/gosnowflake/pull/999
